version: '3'

services:
  server:
    image: php:8-apache
    container_name: server
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./src/public:/var/www/html

  db:
    image: mariadb
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog-laravel
    ports:
      - 3306:3306
    volumes:
      - ./db_blog-laravel:/var/lib/mysql

  myadmin:
    image: phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
